CREATE TABLE contacts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    DEPT_NAME VARCHAR(100),
    NAME VARCHAR(100),
    DEPT VARCHAR(50),
    NUMBER VARCHAR(20),
    EXTENSION VARCHAR(100),
    EMAIL VARCHAR(100)
);

INSERT INTO contacts ( DEPT_NAME, NAME, DEPT, NUMBER, EXTENSION, EMAIL)
VALUES ('IT','Benedek L.', 4, 236, 4236, 'benedek@hype.com');


